#! /bin/bash

/home/build/static/projects/jobcontroller/jc --jobcontroller_server_bns=/bns/iy/borg/iy/bns/wenxuancai/jobcontroller/0:jc create --workflow=entities_builder --epoch=$1 --borgconfig=production/borg/travel-assistant/iy/entities_builder.borg   --vars=mpm_version_entities_builder=$2
